version: "3.7"

services:
  logs-db:
    image: "mongo"
    restart: always
    volumes:
      - logs:/data/db
  web-back-end:
    build: ./web-back-end
    ports:
      - 80:80
      - 443:443
      - 22:22
    working_dir: /app

volumes:
  logs:
